--Basic SQL analysis

-- 1. Retrieve all successful bookings:
SELECT
	*
FROM
	AHMEDABAD_RIDES
WHERE
	BOOKING_STATUS = 'Success';
-- 2. Find the average ride distance for each vehicle type:
SELECT
	VEHICLE_TYPE,
	AVG(RIDE_DISTANCE) AS AVG_DISTANCE
FROM
	AHMEDABAD_RIDES
GROUP BY
	VEHICLE_TYPE;
-- 3. Get the total number of cancelled rides by customers:
SELECT
	COUNT(*) AS CUSTOMER_CANCELLED_RIDES
FROM
	AHMEDABAD_RIDES
WHERE
	BOOKING_STATUS = 'Cancelled by Customer';
-- 4. List the top 5 customers who booked the highest number of rides:
SELECT
	COUNT(*) AS TOTAL_RIDES,
	CUSTOMER_ID
FROM
	AHMEDABAD_RIDES
GROUP BY
	CUSTOMER_ID
ORDER BY
	TOTAL_RIDES DESC
LIMIT
	5;
-- 5. Get the number of rides cancelled by drivers due to personal and car-related issues:
SELECT
	COUNT(*) AS Driver_CANCELLED_RIDES
FROM
	AHMEDABAD_RIDES
WHERE
	Driver_cancel_reason = 'Persol & Car related issues';

-- 6. Find the maximum and minimum driver ratings for Prime Sedan bookings:
SELECT
	MAX(DRIVER_RATINGS),
	MIN(DRIVER_RATINGS)
FROM
	AHMEDABAD_RIDES
WHERE
	VEHICLE_TYPE = 'Prime Sedan';

-- 7. Find the average customer rating per vehicle type:
SELECT
	VEHICLE_TYPE,
	AVG(CUSTOMER_RATING) AS AVG_RATING
FROM
	AHMEDABAD_RIDES
GROUP BY
	VEHICLE_TYPE;
-- 8. Calculate the total booking value of rides completed successfully:
SELECT
	SUM(BOOKING_VALUE) AS TOTAL_REVENUE
FROM
	AHMEDABAD_RIDES
WHERE
	BOOKING_STATUS = 'Success';
-- 9. List all incomplete rides along with the reason:
SELECT
	BOOKING_ID,
	INCOMPLETE_RIDES_REASON
FROM
	AHMEDABAD_RIDES
WHERE
	BOOKING_STATUS = 'Incomplete';

--Advance SQL Analysis

-- 📊 1. Revenue by Vehicle Type

-- Find total booking value generated by each vehicle type and sort from highest to lowest revenue.
SELECT
	SUM(BOOKING_VALUE) AS TOTAL_VALUE,
	VEHICLE_TYPE
FROM
	AHMEDABAD_RIDES
GROUP BY
	VEHICLE_TYPE
ORDER BY
	TOTAL_VALUE DESC;

-- 📉 2. Cancellation Rate per Vehicle Type

-- Calculate percentage of rides cancelled by customers for each vehicle type.


-- Shows business thinking.
SELECT vehicle_type,
       COUNT(*) AS total_rides,
       SUM(cancelled_rides_by_customer) AS cancelled_rides,
       ROUND(
           SUM(cancelled_rides_by_customer) * 100.0 / COUNT(*),
           2
       ) AS cancellation_rate_percent
FROM ahmedabad_rides
GROUP BY vehicle_type;
-- 🏙 3. Most Popular Pickup Locations

-- Find top 5 pickup locations with the highest number of bookings.
SELECT
	PICKUP_LOCATION,
	COUNT(BOOKING_ID) AS TOTAL_BOOKINGS
FROM
	AHMEDABAD_RIDES
GROUP BY
	PICKUP_LOCATION
ORDER BY
	TOTAL_BOOKINGS DESC
LIMIT
	5;

-- 🚗 4. Average Ride Distance per Vehicle Type

-- (You may already have similar but improve it)

-- Also include total rides per vehicle type.
SELECT
	COUNT(BOOKING_ID) AS TOTAL_RIDES,
	AVG(RIDE_DISTANCE) AS AVG_DISTANCE,
	VEHICLE_TYPE
FROM
	AHMEDABAD_RIDES
GROUP BY
	VEHICLE_TYPE;
-- ⏱ 5. Average Customer Waiting Time

-- Calculate average CTAT (Customer Time to Arrival) per vehicle type.

-- Helps analyze service quality.
SELECT
	AVG(AVG_CTAT) AS AVG_TIME,
	VEHICLE_TYPE
FROM
	AHMEDABAD_RIDES
GROUP BY
	VEHICLE_TYPE;
-- 🚫 6. Most Common Driver Cancellation Reason

-- Find top 3 driver cancellation reasons.
SELECT
	DRIVER_CANCEL_REASON,
	COUNT(*) AS TOTAL_CANCELLATIONS
FROM
	AHMEDABAD_RIDES
WHERE
	CANCELLED_RIDES_BY_DRIVER = 1
GROUP BY
	DRIVER_CANCEL_REASON
ORDER BY
	TOTAL_CANCELLATIONS DESC
LIMIT
	3;
-- 📍 7. Route With Highest Revenue

-- Find pickup location → drop location pair that generated highest total booking value.
SELECT
	PICKUP_LOCATION,
	DROP_LOCATION,
	SUM(BOOKING_VALUE) AS TOTAL_REVENUE
FROM
	AHMEDABAD_RIDES
GROUP BY
	PICKUP_LOCATION,
	DROP_LOCATION
ORDER BY
	TOTAL_REVENUE DESC
LIMIT
	2;

-- ⭐ 8. Vehicle Type With Highest Customer Rating

-- Find vehicle type with highest average customer rating.
SELECT
	VEHICLE_TYPE,
	AVG(CUSTOMER_RATING) AS AVG_CUSTOMER_RATING
FROM
	AHMEDABAD_RIDES
GROUP BY
	VEHICLE_TYPE
ORDER BY
	AVG_CUSTOMER_RATING DESC
LIMIT
	2;
-- 🚕 9. Repeat Customers

-- Find customers who booked more than 3 rides.

-- Good for retention analysis.
SELECT
	CUSTOMER_ID,
	COUNT(BOOKING_ID) AS TOTAL_RIDES
FROM
	AHMEDABAD_RIDES
GROUP BY
	CUSTOMER_ID
HAVING
	COUNT(BOOKING_ID) > 3
ORDER BY
	TOTAL_RIDES DESC;
-- 📅 10. Daily Revenue Trend

-- Show total booking value per date.

-- Useful for trend analysis.
SELECT
	DATE,
	SUM(BOOKING_VALUE) AS DAILY_REVENUE
FROM
	AHMEDABAD_RIDES
GROUP BY
	DATE
ORDER BY
	DATE;

Select * From ahmedabad_rides;
-- 📊 11. Completion Rate

-- Calculate percentage of rides successfully completed.

-- completion_rate = successful_rides / total_rides
SELECT 
    COUNT(*) AS total_rides,
    SUM(CASE WHEN booking_status = 'Success' THEN 1 ELSE 0 END) AS successful_rides,
    ROUND(
        SUM(CASE WHEN booking_status = 'Success' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS completion_rate_percent
FROM ahmedabad_rides;
-- 🚗 12. Longest Ride

-- Find top 5 rides with highest ride distance.
SELECT
	*
FROM
	AHMEDABAD_RIDES
ORDER BY
	RIDE_DISTANCE DESC
LIMIT
	5;
-- ⚠ 13. Incomplete Ride Analysis

-- Find top reasons for incomplete rides.
SELECT
	INCOMPLETE_RIDES_REASON,
	COUNT(*) AS TOTAL_INCOMPLETE_RIDES
FROM
	AHMEDABAD_RIDES
WHERE
	INCOMPLETE_RIDES = 1
GROUP BY
	INCOMPLETE_RIDES_REASON
ORDER BY
	TOTAL_INCOMPLETE_RIDES DESC;

-- 💰 14. Average Revenue per Ride

-- Calculate average booking value per vehicle type.
SELECT
	AVG(BOOKING_VALUE) AS AVG_VALUE,
	VEHICLE_TYPE
FROM
	AHMEDABAD_RIDES
GROUP BY
	VEHICLE_TYPE;